---
title: "General Discussion for ATC Experiment E1"
author: "R. Boag"
date: ''
output:
  pdf_document: default
  html_document: default
  word_document: default
geometry: margin=1in
header-includes: \usepackage{setspace}\doublespacing
fontsize: 11pt
fig_caption: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
setwd("C:/Users/Russell Boag/Documents/GitHub/DMCATC")
# setwd("~/Software/DMCATC")
pkgs <- c("plyr", "dplyr", "tidyr", "broom", "pander", "xtable", "citr", "bookdown")
# install.packages(pkgs) #install
sapply(pkgs, require, character.only = T) #load

```


# General Discussion

This study used the LBA, a sequential-sampling model of simple choice, to model decision-making performance on a complex, dynamic, multi-stimulus task under different time pressure and PM demand conditions. Our aim was to assess the utility of the LBA in modelling this more complex applied task and, assuming adequate fit, gain insight into the latent cognitive factors driving changes in performance. Our LBA-based model provided good fits to ongoing task and PM accuracies and closely accounted for the full distribution of RTs for both ongoing task and PM responses across all of our experimental manipulations. The model accounted for changes in RT and accuracy across different levels of time pressure and fit all PM cost effects. In addition, the model provided out-of-sample predictions of nonresponse proportions that closely matched empirical nonresponse data. Speed-accuracy trade-off and PM cost effects were predominantly explained by shifts in response threshold. This is consistent with much speed-accuracy trade-off modelling and supports PMDC and delay theory accounts of PM cost. Reactive inhibition between PM and ongoing task stimuli was evident, providing the first replication of Strickland et al. (2017) and supporting Braver's (2012) dual-mechanisms theory of cognitive control. There was no evidence of a PM capacity cost or a reduction in processing quality with time pressure. Instead, processing effiency increased with time pressure and PM demand suggesting increased task focus or the mobilisation of addtional effort under conditions of higher task demand. 


## Time Pressure

Consistent with much choice-RT modelling of speed-accuracy trade-off effects, ongoing task and PM response thresholds decreased under high time pressure. This suggests that when placed under conditions of high time pressure, people proactively reduce the amount of evidence they require to trigger a decision. This facilitates fast responding but comes at a cost to accuracy - effects which were evident in our analyses of manifest RT and accuracy. This account was bourne out in our model exploration work, in which we generated RT and accuracy predictions from models with thresholds averaged out over time pressure conditions. In terms of accuracy, averaging thresholds over high and low time pressure blocks led the model to predict a larger reduction in conflict accuracy under high time pressure than was observed, while conversely predicting a smaller reduction in nonconflict accuracy under high time pressure than was observed. Threshold shifts between time pressure conditions were thus necessary to account for the observed changes in the accuracy of ongoing task responses. In terms of RT, averaging thresholds over high and low time pressure blocks led the model to predict less of a speed-up between low and high time pressure blocks than was observed for both ongoing task and PM responses. This provides further support for the idea that the primary effect of lowering thresholds under high time pressure is to facilitate faster responding.

Time pressure also affected the bias between conflict and nonconflict response thresholds. Specifically, bias tended to shift from favoring nonconflict responses under low time pressure to favoring conflict responses under high time pressure. This is in line with the work of Loft, Bolland, Humphreys, and Neal (2009), who argue that air-traffic controllers apply larger safety margins by strategically shifting bias towards conflict responses when placed under greater time pressure. Although this strategy increases the rate of conflict false alarms, controllers adopt it because they are motivated to ensure the safety of aircraft over strictly accurate conflict-nonconflict discrimination (Loft, et al., 2009). This finding supports the idea that controller are able to make deliberate strategic adjustments to threshold bias in order to avoid failing to detect potential conflicts. This highlights the dynamic ways in people strategically adapt their performance in order to balance the requirements of two competing task goals (i.e., safety vs speed). 

In addition to reduced response thresholds and strategic shifts in response bias, accumulation rates _increased_ under high time pressure. Model exploration, in which accumulation rates were averaged out over time pressure conditions, indicated that the primary consequence of this rate increase was to speed-up responding in high time pressure blocks. This effect was somewhat suprising as it runs counter to several modelling studies in which accumulation rates were lower in high time pressure blocks compared to low time pressure blocks (Heathcote & Love, 2012; Heitz & Schall, 2012; Ho, Brown, van Maanen, Forstmann, Wagenmakers, & Serences, 2012; Rae, et al., 2014; Starns, Ratcliff, & McKoon, 2012; Vandekerckhove, Tuerlinckx, & Lee, 2008). These accounts typically attribute reduced accumulation rates under time pressure to a reduction in the quality of information entering the decision process, either because less diagnostic information is available from the stimulus during the shorter response window, or because certain cognitive processes become less efficient at extracting stimulus information. Our finding, which points in the opposite direction to these studies, suggests that these kinds of time-induced processing limitations are not present - at least at the longer timescales over which our ATC decisions were made. 

The rate increases we observed here are, however, consistent with several accounts of distraction and mind-wandering which suggest higher task demand reduces the frequency of task-unrelated thoughts (McVay & Kane, 2009; Rummel, Smeekens, & Kane, 2016; Smallwood, 2013; Smallwood & Schooler, 2015). Reducing thoughts unrelated to the task, it is argued, has the ultimate effect of increasing the degree to which subjects focus on or engage with the task at hand. The rate increases evident here may thus reflect greater engagement with the task during high time pressure blocks. 

Alternatively, these rate increases are also consistent with theories of motivation and effort mobilisation which argue that additional cognitive resources can be voluntarily invested into a task by exerting extra effort under conditions of high task demand (Hockey, 1997; Hockey, Coles, & Gaillard, 1986; Kleinsorge, 2001; Sanders, 1983; Schmidt, Kleinbeck, & Brockmann, 1984; Sptiz, 1988; Wickens, 1986). Under this account, rate increases under high time pressure would reflect the deployment of additional cognitive resources that are typically held in reserve during the less demanding low time pressure blocks. We note that there is strong neurological support for this idea, with many studies showing that exerting extra effort can increase the probability of neurotransmitter release, thus potentiating neural structures related to cognitive processing and facilitating the flow of information (Banquet, Smith, & Guenther, 1992; Beierholm, Guitart-Masip, Economides, Chowdhury, Düzel, Dolan, Dayan, 2013; Botvinick & Braver, 2015; Chiew & Braver, 2013; Gallistel, 1985; Jimura, Locke, & Braver, 2010; Niv, Daw, & Dayan, 2007; Schmidt, Lebreton, Clrey-Melin, Daunizaeu, & Pessiglione, 2012). An interesting avenue for future research would be to map neural activity to changes in model parameters under different time pressure and effort mobilisation conditions. 


## PM Demand

### Proactive Control

Consistent with strategic delay and PMDC theories of PM cost (Heathcote, et al., 2015; Horn & Bayen, 2015; Strickland, et al., 2017a; 2017b), ongoing task response thresholds were higher in PM blocks compared to control blocks. This supports the idea that response thresholds are the primary driver of PM cost effects (i.e., slowed ongoing task RT during PM blocks). Specifically, adding a requirement to hold a PM intention and monitor for PM targets alongside a primary ongoing task leads people to raise their ongoing task response thresholds. Raising ongoing task thresholds reduces the likelihood that the ongoing task accumulators will out pace the PM accumulator. This gives the PM accumulator more time to compete for response selection, with the result that fewer PM targets are erroneously preempted by the more habitual ongoing task responses. This idea, that ongoing task thresholds facilitate PM accuracy, was supported by model exploration work in which we compared predicted PM accuracy for a model with the proactive control mechanism turned off (i.e., ongoing task PM block thresholds were set equal to ongoing task control block thresholds). The model with no proactive control predicted PM accuracy to be 17.48% lower than was actually observed, thus confirming the important role of ongoing task threshold shifts in facilitating accurate responses to PM targets. We note that this quantification of the importance of a specific cognitive mechanism on PM accuracy was not possible in previous PM modelling in which PM trials were excluded from analyses (e.g., Heathcote et al., 2015; Horn & Bayen, 2015; Strickland et al., 2017), thus highlighting the utility of our approach.

Further model exploration work, in which we generated RT and accuracy predictions from models with thresholds averaged out over control and PM blocks, showed that proactive threshold shifts are important drivers of differences in both accuracy and RT between control and PM conditions. In terms of accuracy, averaging thresholds over control and PM blocks leads the model to predict a larger cost to ongoing task accuracy in PM blocks than is actually observed. Adopting higher ongoing task thresholds under PM load therefore plays a role in maintaining accurate ongoing task performance in the presence of additional PM demands. In terms of RT, averaging thresholds over control and PM blocks leads the model to predict much faster ongoing task RTs in PM blocks than is actually observed. The higher ongoing task thresholds in PM blocks is therefore the primary driver of the much slower ongoing task RTs observed under PM demand. This finding adds to a growing number of studies showing that PM costs are primarily driven by strategic shifts in response thresholds (Heathcote, et al., 2015; Horn & Bayen, 2015; Strickland, et al., 2017a; 2017b).

In addition, PM-induced proactive control of thresholds interacted with time pressure. Specifically, the magnitude of ongoing task threshold adjustments between control and PM blocks got smaller as time pressure increased. That is, strategic adjustments to PM demand were less effective under high time pressure compared to low time pressure. To our knowledge this is the first time a study has shown strategic adjustments to PM demand interacting with another task-demand variable. This finding suggests operators may be more prone to making PM errors under high time pressure, which may have important safety implications for applied settings in which operators deal with frequent changes in PM and time pressure demands.


### Reactive Control

Consistent with the reactive inhibition predictions of PMDC, ongoing task accumulation rates were lower PM trials compared to non-PM trials. That is, accumulation rates were lower for ongoing task stimuli when a PM cue was present compared to rates for the same stimuli with PM cue absent. This is the first replication of Strickland, et al., (2017) and supports the idea that, when a PM stimulus is present, the PM stimulus detector shunts inhibitory input to the competing ongoing task accumulators. This increases the probability that the PM accumulator will reach threshold and trigger a PM response before the ongoing task accumulators. In addition, stronger reactive inhibition effects occurred for the correct (congruent) ongoing task accumulator compared to the incorrect (incongruent) ongoing task accumulator. That is, correct ongoing task responses were inhibited more than incorrect ongoing task responses. This suggests response inhibition processes may be to some degree stimulus-specific; selectively targeting the ongoing task response most saliently competing with the PM accumulator for response selection. 

As with the proactive control mechanism, our model exploration showed that this reactive inhibition mechanism is also an important driver of PM accuracy and RT. Removing the reactive inhibition mechanism led the model to underpredict PM accuracy by almost 10 percent and RT by around 4 percent, thus lending some support to the idea that inhibition of ongoing task accumulation rates on PM trials facilitates accurate performance of the PM task. This replicates Strickland et al. (2017), who found that the reactive control mechanism was necessary to account for the slow but accurate PM responses observed in their data. We note that although reducing ongoing task drift rates via inhibition would typically produce slower ongoing task RTs on PM trials, these were not observed in the data. However, as noted by Strickland et al. (2017) this is likely due to statistical facilitation from the PM accumulator. Specifically, on PM trials the ongoing task accumulators must compete for response selection with the much faster PM accumulator, meaning that any observed ongoing task responses on PM trials had to be fast enough to outpace the PM response accumulator. As such, PM trials tend to be associated with faster or equivalent ongoing task RTs than non-PM trials (Raaja, 1962), an effect also predicted in earlier model simulations of PM performance (Gilbert, et al., 2013).


### Effort Mobilisation and Task Focus under PM Load

Contrary to the predictions of capacity-sharing theories of PM cost (Boywitt & Rummel, 2012; Craik, 1986; Einstein & McDaniel, 2005; Marsh & Hicks, 1998; Park, Hertzog, Kidder, Morrel, & Mayhorn, 1997; Smith, 2003), we found that ongoing task accumulation rates for both correct and error responses actually increased with the addition of PM load. This overall improvement in processing efficiency runs opposite to capacity-sharing accounts which predict a reduction in accumulation rates under PM load. Model exploration, in which we generated RT and accuracy predictions from models with accumulation rates averaged out over control and PM blocks, showed that rates played an important role in explaining of differences in accuracy and RT between control and PM conditions. In terms of accuracy, averaging rates over control and PM blocks led the model to predict a smaller cost to ongoing task accuracy in PM blocks than was actually observed. The higher ongoing task rates under PM load therefore played a role in reducing the accuracy of ongoing task performance in the presence of additional PM demands. This is likely because, although both correct and error accumulation rates increased under PM load, error accumulation rates increased more than correct accumulation rates, having a negative effect on accuracy. In terms of RT, averaging rates over control and PM blocks led the model to predict much slower ongoing task RTs in PM blocks than was actually observed. The higher ongoing task rates in PM blocks therefore serves to speed up ongoing task performance - counteracting at least some of the RT cost induced by setting more conservative thresholds in PM blocks. 

One explanation for why rates might increase under PM load comes from studies looking at the effects of mind-wandering on task engagement (Kane & McVay, 2012; McVay & Kane, 2009; Rummel, Smeekens, & Kane, 2016; Smallwood, 2013; Smallwood & Schooler, 2015). These studies suggest that processing efficiency can actually improve with the addition of task demand because more cognitively demanding task conditions allow fewer opportunities to engage in thoughts unrelated to the task at hand. That is, during conditions of high task demand, participants engage in less mind-wandering and have fewer task-unrelated thoughts; the result being that high-demand tasks are performed with greater focus and engagement than low-demand tasks, which are less cognitively engaging and more prone to mind-wandering (Giambra, 1989; Kane & McVay, 2012; Rummel, Smeekens, & Kane, 2016). Although our ATC conflict detection task is more cognitively demanding than typical lab paradigms (as evidenced by the relatively low accuracies and long RTs reported here) even without the additional PM demand, it is nevertheless plausible that the differences in processing efficiency between control and PM blocks are partly due to differences in task engagement between the two conditions. Specifically, control blocks may have been associated with a greater degree of mind-wandering and task-unrelated thoughts (i.e., less task engagement) which would negatively affect the efficiency of information processing or evidence accumulation. Conversely, the addition of the PM requirement may have been associated with less mind-wandering and fewer task-unrelated thoughts (i.e., more task engagement), thus improving the efficiency with which information was processed or evidence accumulated. Future work would do well to include measures of mind-wandering and task engagement (e.g., Rummel, Smeekens, & Kane, 2016) in order to lend convergent support for such an account. 

Alternatively, increased accumulation rates under PM load may have been the result of a more volitional process in which participants increased their overall effort in response to greater task demands. This account is consistent with research on effort mobilisation and motivation, which has suggested people can draw on a pool of cognitive resources 'held in reserve'; allowing them to voluntarily allocate extra resources (e.g., attention, working memory) to a task when motivated to do so (Hockey, 1997; Hockey, Coles, & Gaillard, 1986; Kleinsorge, 2001; Sanders, 1983; Schmidt, Kleinbeck, & Brockmann, 1984; Sptiz, 1988; Wickens, 1986). As noted, there is strong neurological support for this idea; studies have shown that deliberate increases in effort potentiate neural structures related to cognitive processing, for example by increasing the probability that certain neurotransmitters will be released (Banquet, Smith, & Guenther, 1992; Beierholm, Guitart-Masip, Economides, Chowdhury, Düzel, Dolan, Dayan, 2013; Botvinick & Braver, 2015; Chiew & Braver, 2013; Gallistel, 1985; Jimura, Locke, & Braver, 2010; Niv, Daw, & Dayan, 2007; Schmidt, Lebreton, Clrey-Melin, Daunizaeu, & Pessiglione, 2012). This has the effect of boosting processing intensity or increasing the signal strength of evidence sampled from stimuli, thus facilitating the flow of information (Kleinsorge, 2001; Wickens, 1986). 

In the present context it is possible that participants were motivated to exert extra effort or deploy more cognitive resources in PM blocks in response to the greater perceived task demands. This account is supported by our NASA-TLX measure, whereby self-reported effort and perceived mental demand ratings were both significantly higher in PM blocks compared to control blocks. Moreover, effort exertion ratings were significantly positively correlated with ongoing task accumulation rates, but only for the incorrect response accumulators. That is, higher self-reported effort was related to higher error accumulation rates. It therefore seems as though subjects can choose to deploy more cognitive resources into the task when changes in environmental conditions suggest it may be advantageous to do so. Crucially, such resources need not be diverted from the ongoing task, contrary to the claims of capacity-sharing explanations. However, it is interesting to note that error accumulation rates for the ongoing task were more related to effort ratings than were correct accumulation rates. This suggests that although it appears people can increase the rate of information processing through volitional changes in effort, that extra effort does not necessarily translate into higher quality information processing. 

It is unclear by what specific mechanism exerting extra effort would lead to increased error accumulation rates while leaving correct rates unaffected, however there are several possibilities. If effort corresponds to an overall increase in gain or the largely indescriminate potentiation of entire cognitive structures, then the attendant increases in processing speed may not affect correct and error accumulators uniformly. To use a neural analogy, it may be easy to boost the relatively weak firing of a neuron signalling incorrect stimulus information, but much harder to increase the already strong firing of a neuron signalling correct stimulus information, which may already be firing at some ceiling rate. As such, an overall increase in potentiation might be akin to increasing the false-alarm rate. An interesting avenue for future research would be to further tease apart why effort exertion appears to be related to accumulation rates for error responses but not for correct responses. 


### Capacity-Sharing

As noted, the increased ongoing task accumulation rates we observed in response to PM demand run counter to capacity-sharing accounts of PM cost (Boywitt & Rummel, 2012; Craik, 1986; Einstein & McDaniel, 2005; Marsh & Hicks, 1998; Park, Hertzog, Kidder, Morrel, & Mayhorn, 1997; Smith, 2003). Our rate effects run in opposite directions to what would be expected if cognitive resources (e.g., prepatory attention, working memory) were being diverted from the ongoing task and deployed towards processes responsible for maintaining PM intentions or monitoring for PM targets. Moreover, we note that our cognitively-demanding ATC task, coupled with a completely non-focal PM cue would arguably have produced ideal conditions for capacity-cost effects to emerge. As such, the present findings provide convincing evidence against a capacity-sharing explanation of PM costs. This adds to a growing number of studies that have failed to find accumulation rate effects consistent with capacity-sharing theories of PM cost (Ball & Aschenbrenner, 2017; Heathcote, et al., 2015; Horn & Bayen, 2015; Strickland, et al., 2017a; 2017b). 

It should be noted, however, that we do not claim that PM processes do not rely on cognitive resources at all. What we are suggesting is that the resources involved in PM processing are not necessarily diverted from the ongoing task and do not necessarily interfere with the quality of ongoing task information processing (see also Strickland, et al., 2017). Indeed, our finding of increased ongoing task accumulation rates under PM load is more in-line with the idea that PM resources are drawn from a reserve pool of resources largely unrelated to ongoing task processing. That said, we do not suggest capacity sharing between PM and ongoing task resources never occurs. As noted earlier, although the present findings suggest capacity-cost effects are largely inconsequential in terms of explaning manifest PM costs, our analysis cannot unequivocably say that no capacity-sharing occurred. Indeed, it may be the case that a small capacity-cost (i.e., reduction in rates) occurred, but was overwhelmed by a much larger increase in rates due to the mobilisation of additional resources or enhanced task focus in PM blocks. Nevertheless, the large, opposite-direction effects observed here, with non-focal PM targets and cognitively-demanding ATC task, do diminish the role of capacity-sharing in PM. Designing experiments that can tease apart these processes would be a good avenue for future research and certainly further PM theory. 


## Implications for Applied Research

The above discussion highlights the wide variety of ways - both deliberate and automatic - in which operators are able to adapt to changes in task demands. Importantly for applied research, our model-based analysis identifies the often complex ways in which numerous latent cognitive processes contribute to observed changes in the speed and accuracy of PM and ongoing task decisions. Moreover, we are able to show how such processes combine and interact with each other in response to changes in time pressure, trial load, and PM demands - factors frequently implicated in performance decrements across a wide range of safety-critical work settings. The fine-grained level of analysis presented here is critical for the development of effective and efficient interventions (e.g., automation, training, decision aides) able to target the specific cognitive processes responsible for performance decrements in different conditions. 

For example, this work has shown that deliberate threshold adjustments are the primary driver of ongoing task RT costs under PM load. 




## Limitations and Future Directions

- Time-based PM





## Conclusion

In summary, people use a wide variety of cognitive control mechanisms to adapt to changes in task demands. These include reactive control mechanisms: automatic and outside of conscious control, and proactive control mechanisms: volitional, strategic adjustments consciously deployed in response to changing task demands. This study has shown the numerous and often complex ways these control mechanisms are engaged under different levels of time pressure and prospective memory demand, thus highlighting the importance of accounting for these processes in applied research and in developing models of applied tasks. Finally, we reiterate that many of the inferences drawn here would simply not have been possible via conventional analyses of mean RT and accuracy alone. This highlights the utility of formal modelling in investigating decision-making and its importance in drawing inferences about how individuals make decisions and adjust their strategies in response to changing demands in complex dynamic task environments. 
